version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongodb:27017/myapp
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

